function [ success ] = init
% Init file
success = logical( 0 );

if (libisloaded('rec_robotino_api2') ~= 1)
	robotinoAPI2_32_Dir = getenv('ROBOTINOAPI2_32_DIR');
	robotinoAPI2_64_Dir = getenv('ROBOTINOAPI2_64_DIR');

	switch computer
		case 'PCWIN'
			robotinoMatlabLIB = strcat( robotinoAPI2_32_Dir, '\bin' );
			robotinoMatlabINC1 = strcat( robotinoAPI2_32_Dir, '\include\rec\robotino\api2\c' );
			robotinoMatlabINC2 = strcat( robotinoAPI2_32_Dir, '\include' );
		case 'PCWIN64'
			robotinoMatlabLIB = strcat( robotinoAPI2_64_Dir, '\bin' );
			robotinoMatlabINC1 = strcat( robotinoAPI2_64_Dir, '\include\rec\robotino\api2\c' );
			robotinoMatlabINC2 = strcat( robotinoAPI2_64_Dir, '\include' );
		otherwise
			success = logical( 0 );
	end;

    path( robotinoMatlabLIB, path );
    path( robotinoMatlabINC1, path );
    loadlibrary( 'rec_robotino_api2.dll', 'Com.h', ...
        'includepath', robotinoMatlabINC2, ...
        'addheader', 'OmniDrive', ...
        'addheader', 'Camera', ...
        'addheader', 'Bumper', ...
        'addheader', 'Motor', ...
        'addheader', 'NorthStar', ...
        'addheader', 'Odometry', ...
        'addheader', 'AnalogInput', ...
        'addheader', 'DigitalInput', ...
        'addheader', 'DigitalOutput', ...
        'addheader', 'DistanceSensor', ...
        'addheader', 'EncoderInput', ...
        'addheader', 'Gripper', ...
        'addheader', 'Info', ...
        'addheader', 'PowerManagement', ...
        'addheader', 'PowerOutput', ...
        'addheader', 'Relay', ...
        'addheader', 'Manipulator', ...
        'addheader', 'LaserRangeFinder', ...
		'addheader', 'CompactBHA', ...
        'addheader', 'Kinect', ...
        'alias', 'rec_robotino_api2' );
    disp( 'rec_robotino_api2.dll loaded.' );
    success = logical( 1 );
else
    success = logical( 1 );
end;
    